name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: azure/login@v2
        with:
         creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Upload code to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          resource-group: "demo-resources"  # Replace with your resource group name
          app-name: "demoappserviceajir665t"  # Replace with your app service name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
